name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
      - name: Compile
        shell: bash
        run: |
          PROM_FOLDER=$(pwd)/lib/prom
          PROMHTTP_FOLDER=$(pwd)/lib/promhttp

          $PROM_FOLDER
          mkdir build
          cd build
          cmake ..
          make
          sudo make install

          cd ..
          cd ..
          
          $PROMHTTP_FOLDER
          mkdir build
          cd build
          cmake ..
          make
          sudo make install

          cd ..
          cd ..
          cd ..

          mkdir build
          cd build
          cmake ..
          make all