name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
      - name: Compile
        shell: bash
        run: |
          cd $(pwd)/lib/prom-c-client/prom
          mkdir build
          cd build
          cmake ..
          make
          sudo make install

          cd ..
          cd ..
          
          cd promhttp
          mkdir build
          cd build
          cmake ..
          make
          sudo make install

          cd ..
          cd ..
          cd ..
          cd ..

          mkdir build
          cd build
          cmake ..
          make all