name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
      - name: Compile
        shell: bash
        run: |
          SRC_FOLDER=$(pwd)/src
          LIB_FOLDER=$(pwd)/lib
          cd $LIB_FOLDER/prom/
          
          
          make all
