name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
      - name: Compile
        shell: bash
        run: |
          SRC_FOLDER=$(pwd)/src
          
          # TODO - Install prom and promhttp with cmake
          # TODO - Use cmake to compile main program

           
          make all
