name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
      - name: Compile
        shell: bash
        run: |
          SRC_FOLDER=$(pwd)/src
          PROM_FOLDER=$(pwd)/prom
          PROMHTTP_FOLDER=$(pwd)/promhttp

          cd $PROM_FOLDER
          mkdir build
          cd build
          cmake ..
          make
          sudo make install

          cd ..
          cd ..
          
          cd $PROMHTTP_FOLDER
          mkdir build
          cd build
          cmake ..
          make
          sudo make install

          cd..
          cd..

          mkdir build
          cd build
          cmake ..
          make all